
#This workflow runs the hugo command to build the site and then 
#pushes the newly built site to https://github.com/SusanStrange/SusanStrange.GitHub.io
name: Site Builder and Deployer

#This makes the action trigger on any push or commit to the master branch of the repository
on:
  #push:
  #  branches: [ master ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #This task checks out the git repository so it can be used by your workflow and action
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 1   
      #This task sets up hugo in the actions environment
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      #This task sets up Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      #This is a debug task
      - name: Testing
        run: |
          npm install
          dir
          echo "completed"
          
      #This task executes the hugo build command
      #- name: Build
      #  run: hugo

      #This task takes the newly built version of the site and pushes it to the Front_End repository
      #- name: Deploy
       # uses: peaceiris/actions-gh-pages@v3
        #with:
         # personal_token: ${{ secrets.PERSONAL_TOKEN }}
          #external_repository: BrockDSL/BrockDSL.github.io
          #publish_branch: master
          #publish_dir: ./public

